spring:
  datasource:
    druid:
    url: jdbc:mysql://localhost:3306/graduate?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initial-size: 1
    min-idle: 1
    max-active: 20
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.example.salary.domain


#thymeleaf:
#  prefix: classpath:/html/
#  suffix: .html
#  mode: HTML5
#  encoding: utf-8
#  cache: false
#  content-type: text/html