spring:
  datasource:
    druid:
    url: jdbc:mysql://localhost:3306/supermarket?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initial-size: 1
    min-idle: 1
    max-active: 20
#mybatis:
#  mapper-locations: classpath:mappers/*Mapper.xml
#  type-aliases-package: com.example.supermarket.ws.domain
